features/moderation
Coding-with-Efehan/CWE pull request #9
Opened 2021-06-24 08:34 UTC by quinchs

# Summary
This PR adds the base moderation commands and functions, as well as some useful services/handlers associated with the moderation code.

# Changes
### Interaction Service
The interaction service is designed to act like the interactivity service, it allows you to use `NextButtonAsync` and `NextSlashCommandAsync`.

### Moderation Handler
The moderation handler is the core of this PR, It's what takes in infractions and computes them. It's responsible for logging infractions, kicking/muting/banning users, mutes, and storing infractions.

### Moderation Module
This module contains all the moderation commands for CWE.
| Command name | Parameters                    | Description                                      |
|--------------|-------------------------------|--------------------------------------------------|
| warn         | `<@user> <reason>`            | Warns a user.                                    |
| kick         | `<@user> <reason>`            | Kicks a user from the CWE guild                  |
| ban          | `<@user> <reason>`            | Bans a user from the CWE guild                   |
| mute         | `<@user> <duration> <reason>` | Mutes a user for a given amount of time.         |
| infractions  | `<@user>`                     | Gets a list of the specified user's infractions. |

### RequreStaff Precondition Attribute
This attribute is designed for usage on commands, it extends the `PreconditionAttribute` class from Discord.Net.Commands. Attaching this attribute to your command will restrict its usage to only staff members of the CWE discord server.

# appsettings.json additions
This PR adds 3 new config fields

| Field location         | Type  | Description                                                                                               |
|------------------------|-------|-----------------------------------------------------------------------------------------------------------|
| Channels -> LogChannel | ulong | The channel to send moderation logs to.                                                                   |
| Roles -> Staff         | ulong | The staff role id. This Id is whats used to check whether or not a user can execute a moderation command. |
| Roles -> Muted         | ulong | The role to give when someone is muted with the `mute` command.                                           |

2021-06-24 16:39 UTC, n-Ultima commented
Why make "Mute" it's own object? You can instead make an InfractionType Enum, or something like that. Now you have InfractionType.Warn, InfractionType.Mute, etc etc

2021-06-25 09:08 UTC, Directoire requested changes
Thank you for this very useful PR! I would however like to see a bit more consistency with i.e. the creation of embeds. Where you sometimes use `.WithFields()`, in the original source we use `.AddField()`. Could you go over your code and ensure that both the methods that you use, as well as the syntax is consistent with the original code? This includes i.e. the use of colors (we have a colors class that includes a `success` color).

2021-06-25 09:08 UTC, hendrikdemir commented on CWE.Data/DataAccessLayer.cs
> +            await this.dbContext.Infractions.AddAsync(infraction);
In the DAL we don't use `AddAsync()`, please simply use `Add()`.

2021-06-25 09:08 UTC, hendrikdemir commented on CWE.Data/DataAccessLayer.cs
> +        }
```suggestion
        public async Task<IReadOnlyCollection<Infraction>> GetInfractions(ulong userId)
        {
            return await this.dbContext.Infractions.Where(x => x.UserId == userId).ToListAsync();
        }
```
Can be moved into one line and changed the name as there is no `GetInfractions()` (more consistent naming).

2021-06-25 09:08 UTC, hendrikdemir commented on CWE.Data/DataAccessLayer.cs
> +            await this.dbContext.Mutes.AddAsync(mute);
See the previous comment about the use of `AddAsync()`.

2021-06-25 09:08 UTC, hendrikdemir commented on CWE.Data/DataAccessLayer.cs
> +
Unnecessary whitespace

2021-06-25 09:08 UTC, Directoire commented on CWE.Data/Models/Infraction.cs
> +    }
The usernames of members and staff members should not be stored as they can change over time and therefore cause confusion. Rather, only store the ids as properties `User` and `Staff`.

2021-06-25 09:08 UTC, Directoire commented on CWE.Data/Models/Mute.cs
> +        public DateTime MuteEnd { get; set; }
```suggestion
        /// <summary>
        /// Gets or sets the time the mute started.
        /// </summary>
        public DateTime Start { get; set; }

        /// <summary>
        /// Gets or sets the time the mute ends.
        /// </summary>
        public DateTime End { get; set; }
```
Renaming of the properties as the class name is already mute, no need to prefix the properties with the name of the class they're in.

2021-06-25 09:08 UTC, Directoire commented on CWE.Data/Models/Mute.cs
> +        public Guid InfractionId { get; set; }
Is there any reason this is called an `InfractionId`? I don't see a relationship to the infractions table, shouldn't this just be an id or `MuteId`?

2021-06-25 09:08 UTC, Directoire commented on CWE/Common/Extensions.cs
> +                Name = $"{user.Username}{user.Discriminator}",
```suggestion
                Name = $"{user.Username}#{user.Discriminator}",
```
Add the # between the username and discriminator.

2021-09-22 15:17 UTC, n-Ultima commented
Just because I'm bored and I decided to go over this, why exactly is the `Mute` model even there? Why not simply have a nullable `TimeSpan?` duration on the `Infraction` model? You can also simply add in a `DateTimeOffet?` for when the infraction should expire.

2021-09-22 15:21 UTC, n-Ultima commented
That, and I see an `async void` method in `ModerationHandler.cs`. Won't that crash the program if any exception is thrown at all?

2021-11-15 09:40 UTC, Directoire commented
Hi @quinchs, do you have any updates to solve the comments?

2021-11-26 09:57 UTC, Directoire commented
Closed as there were no further updates, thank you for the PR :)

2021-11-26 09:57 UTC, closed without merging